SQL_EXAMPLES = [
            "Generate SQL given the question and table for selecting the required rows and columns to answer the question correctly.\nFollowing are some examples:",
            "",
            "Table_title: Marek Plawgo",
            "Table_columns: ['Year', 'Competition', 'Venue', 'Position', 'Event', 'Notes']",
            "Question: when was his first 1st place record?",
            "output: Let's think step by step.",
            "columns: ['Year',  'Position']",
            "sql: select Year, Position from T where Position like '%1st%'",
            "",
            "Table_title: 2013\u201314 Toros Mexico season",
            "Table_columns: ['Game', 'Day', 'Date', 'Kickoff', 'Opponent', 'Results_Score', 'Results_Record', 'Location', 'Attendance']",
            "Question: what was the number of people attending the toros mexico vs. monterrey flash game?",
            "output: Let's think step by step.",
            "columns: ['Attendance’, 'Opponent']",
            "sql: select Opponent, Attendance from T where Opponent like '%monterrey flash%'",
            "",
            "Table_title: Radhika Pandit",
            "Table_columns:  ['Year', 'Film', 'Role', 'Language', 'Notes']",
            "Question: what is the total number of films with the language of kannada listed?",
            "output: Let's think step by step.",
            "columns: ['Film', 'Language']",
            "sql: select Film, Language from T where Language like '%kannada%'",
            "",
            "Table_title: List of storms on the Great Lakes",
            "Table_columns:  ['Ship', 'Type_of_Vessel', 'Lake', 'Location', 'Lives_lost']",
            "Question: how many more ships were wrecked in lake huron than in erie?",
            "output: Let's think step by step.",
            "columns: ['Ship',  'Lake']",
            "sql: SELECT Ship, Lake FROM T WHERE Lake LIKE '%Lake Huron%' or Lake LIKE '%Lake Erie%'",
            "",
            "Table_title: List of hospitals in North Carolina",
            "Table_columns:  ['Name', 'City', 'Hospital_beds', 'Operating_rooms', 'Total', 'Trauma_designation', 'Affiliation', 'Notes']",
            "Question: what is the only hospital to have 6 hospital beds?",
            "output: Let's think step by step.",
            "columns: ['Name', 'Hospital_beds']  ",
            "sql: select Name, Hospital_beds from T where Hospital_beds = 6",
            "",
            "Table_title:Churnet Valley Railway ",
            "Table_columns:  ['Number', 'Name', 'Type', 'Livery', 'Status', 'Notes']",
            "Question: how many locomotives are currently operational?",
            "output: Let's think step by step.",
            "columns: ['Name',  'Status']",
            "sql: select Name, Status from T where Status like '%operational%'",
            "",
            "Table_title: List of hospitals in North Carolina",
            "Table_columns:  ['Rank', 'Nation', 'Gold', 'Silver', 'Bronze', 'Total']",
            "Question: who won the most gold medals?",
            "output: Let's think step by step.",
            "columns: ['Nation', 'Gold'] ",
            "sql: select Nation, Gold from T",
            "",
            "Table_title: 2012–13 Exeter City F.C. season",
            "Table_columns:  ['Name', 'League', 'FA_Cup', 'League_Cup', 'JP_Trophy', 'Total']",
            "Question: does pat or john have the highest total?",
            "output: Let's think step by step.",
            "columns: ['Name', 'Total']",
            "sql: select Name, Total from T where Name like '%pat%' or Name like '%john%'",
            "",
            "Table_title: My Brother and Me",
            "Table_columns:  ['Series_', 'Season_', 'Title', 'Notes', 'Original_air_date']",
            "Question: alfie's birthday party aired on january 19. what was the airdate of the next episode?",
            "output: Let's think step by step.",
            "columns: ['Title', 'Season_', 'Original_air_date']",
            "sql: select Title, Season_, Original_air_date from T",
            "",
            "Table_title: The Harvest (Boondox album)  ",
            "Table_columns:  ['_', 'Title', 'Time', 'Lyrics', 'Music', 'Producers', 'Performers']",
            "Question: how many song come after \"rollin hard\"?",
            "output: Let's think step by step.",
            "columns: ['Title', 'Time']",
            "sql: select Title, Time from T",
            "",
            "Table_title: GameStorm.org",
            "Table_columns:  ['Iteration', 'Dates', 'Location', 'Attendance', 'Notes']",
            "Question: what's the total attendance for gamestorm 11?",
            "output: Let's think step by step.",
            "columns: ['Attendance', 'Iteration']",
            "sql: select Attendance, Iteration from T where Iteration like '%gamestorm 11%'",
            "",
            "Table_title: 1981 Iowa Hawkeyes football team ",
            "Table_columns:  ['Date', 'Opponent', 'Rank', 'Site', 'TV', 'Result', 'Attendance']",
            "Question: which date had the most attendance?",
            "output: Let's think step by step.",
            "columns: ['Date', 'Attendance']",
            "sql: select Date, Attendance from T",
            "\n"]

ANSWER_EXAMPLES = [
            "Here are some examples of how to use table info and query results to answer a question:",
            "",
            "Table: My Brother and Me (Series #,  Season #, Title, Notes, Original air date)",
            "",
            "Series # | Season # | Title | Notes | Original air date",
            "1 | 1 | The Charity | Alfie, Dee Dee, and Melanie are supposed to be helping | October 15, 1994",
            "2 | 1 | The Practical Joke War | Alfie and Goo unleash harsh practical jokes on Dee Dee | October 22, 1994",
            "3 | 1 | The Weekend Aunt Helen Came | The boy's mother, Jennifer, leaves for the weekend and she | November 1, 1994",
            "4 | 1 | Robin Hood Play | Alfie's school is performing the play Robin Hood and Alfie | November 9, 1994",
            "5 | 1 | Basketball Tryouts | Alfie tries out for the basketball team and doesn't make | November 30, 1994",
            "6 | 1 | Where's the Snake? | Dee Dee gets a snake, but he doesn't want his | December 6, 1994",
            "7 | 1 | Dee Dee's Girlfriend | A girl kisses Dee Dee in front of Harry and | December 15, 1994",
            "8 | 1 | Dee Dee's Haircut | Dee Dee wants to get a hair cut by Cool | December 20, 1994",
            "9 | 1 | Dee Dee Runs Away | Dee Dee has been waiting to go to a monster | December 28, 1994",
            "10 | 1 | 'Donnell's Birthday Party | Donnell is having a birthday party and brags about all | January 5, 1995",
            "11 | 1 | Alfie's Birthday Party | Goo and Melanie pretend they are dating and they leave | January 19, 1995",
            "12 | 1 | Candy Sale | Alfie and Goo are selling candy to make money for | January 26, 1995",
            "13 | 1 | The Big Bully | Dee Dee gets beat up at school and his friends | February 2, 1995",
            "",
            "Question: alfie's birthday party aired on january 19. what was the airdate of the next episode?",
            "A: To find the answer to this question, let’s think step by step. From the table, we can look into the ’Title’ column and find that the next episode after ‘Alfie’s Birthday Party’ is ‘Candy Sale’. The ‘Original air date’ of ‘Candy Sale’ is January 26, 1995.",
            "Therefore, the answer is January 26, 1995.",
            "Answer: January 26, 1995 ",
            "",
            "Table: Radhika Pandit (Year, Film, Role, Language, Notes)",
            "",
            "Year | Film | Role | Language | Notes",
            "2008 | Moggina Manasu | Chanchala | Kannada | Filmfare Award for Best Actress - Kannada Karnataka State Film Award",
            "2009 | Olave Jeevana Lekkachaara | Rukmini | Kannada | Innovative Film Award for Best Actress",
            "2009 | Love Guru | Kushi | Kannada | Filmfare Award for Best Actress - Kannada",
            "2010 | Krishnan Love Story | Geetha | Kannada | Filmfare Award for Best Actress - Kannada Udaya Award for Best",
            "2010 | Gaana Bajaana | Radhey | Kannada | ",
            "2011 | Hudugaru | Gayithri | Kannada | Nominated, Filmfare Award for Best Actress – Kannada",
            "2012 | Alemari | Neeli | Kannada | ",
            "2012 | Breaking News | Shraddha | Kannada | ",
            "2012 | Addhuri | Poorna | Kannada | Udaya Award for Best Actress Nominated — SIIMA Award for Best",
            "2012 | 18th Cross | Punya | Kannada | ",
            "2012 | Sagar | Kajal | Kannada | ",
            "2012 | Drama | Nandini | Kannada | ",
            "2013 | Kaddipudi | Uma | Kannada | ",
            "2013 | Dilwala | Preethi | Kannada | ",
            "2013 | Bahaddoor | Anjali | Kannada | Filming",
            "2014 | Mr. & Mrs. Ramachari |  |  | Announced",
            "2014 | Endendigu |  |  | Filming",
            "",
            "Question: what is the total number of films with the language of kannada listed?",
            "A: To find the answer to this question, let’s think step by step. From the table, we can see that there are several rows where the ‘Language’ column has the value ‘Kannada’. There are 15 rows with the value ‘Kannada’ in the ‘Language’ column.",
            "Therefore, the answer is 15.",
            "Answer: 15"
        ]